companion_crops = {
    "rice": ["lentils", "mustard", "sesame"],
    "maize": ["beans", "pumpkin", "squash"],
    "chickpea": ["mustard", "linseed"],
    "kidneybeans": ["maize", "sunflower"],
    "pigeonpeas": ["sorghum", "groundnut"],
    "mothbeans": ["pearl millet", "sesame"],
    "mungbean": ["maize", "cotton"],
    "blackgram": ["sorghum", "groundnut"],
    "lentil": ["mustard", "linseed"],
    "pomegranate": ["onion", "garlic"],
    "banana": ["ginger", "turmeric"],
    "mango": ["legumes", "vegetables"],
    "grapes": ["beans", "peas"],
    "watermelon": ["maize", "sunflower"],
    "muskmelon": ["maize", "okra"],
    "apple": ["beans", "peas"],
    "orange": ["legumes", "groundnut"],
    "papaya": ["turmeric", "ginger"],
    "coconut": ["pineapple", "banana"],
    "cotton": ["mungbean", "soybean"],
    "jute": ["rice", "sesame"],
    "coffee": ["banana", "pepper"]
}
